import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {ELEMENTS} from './game-data.js';

const ANIMS={idle:['Idle','Flying_Idle'],move:['Run','Fast_Flying','Walk'],attack:['Bite_Front','Punch','Headbutt','Weapon'],hit:['HitRecieve','HitReact'],death:['Death'],victory:['Dance','Wave','Yes']};
const ease=t=>1-Math.pow(1-t,3);

export class PetRenderer{
 constructor(host,{battle=false,quality='high'}={}){this.host=host;this.battle=battle;this.quality=quality;this.mixers=[];this.entities={ally:[],enemy:[]};this.clock=new THREE.Clock();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(battle?34:35,1,.1,100);this.camera.position.set(0,battle?5.4:2.2,battle?12.5:6);this.camera.lookAt(0,battle?1.1:1,0);this.renderer=new THREE.WebGLRenderer({antialias:quality==='high',alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.55:1));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=quality==='high';host.appendChild(this.renderer.domElement);this.loader=new GLTFLoader();this.buildScene();this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.loop()}
 buildScene(){this.scene.add(new THREE.HemisphereLight(0xcce5ff,0x111827,2.6));let key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(4,9,6);key.castShadow=true;this.scene.add(key);let rim=new THREE.PointLight(0x8d72ff,18,18);rim.position.set(-5,5,-2);this.scene.add(rim);let floor=new THREE.Mesh(new THREE.CircleGeometry(this.battle?8:3,48),new THREE.MeshStandardMaterial({color:0x172546,roughness:.72,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor);for(let i=0;i<(this.battle?32:18);i++){let p=new THREE.Mesh(new THREE.IcosahedronGeometry(.025+Math.random()*.04),new THREE.MeshBasicMaterial({color:i%2?0x67e7ff:0xb08cff}));p.position.set((Math.random()-.5)*(this.battle?13:6),.2+Math.random()*4,(Math.random()-.5)*5);p.userData.float=Math.random()*6;this.scene.add(p)}}
 load(template){return new Promise((resolve,reject)=>this.loader.load(`assets/models/${template.model}.glb`,resolve,undefined,reject))}
 makeEntity(gltf,template,instance,pos,side){let root=gltf.scene;root.position.set(pos.x,0,pos.z);root.rotation.y=side==='enemy'?-Math.PI/2:Math.PI/2;let box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),scale=(this.battle?1.55:2.2)/Math.max(size.y,.1);root.scale.setScalar(scale);box.setFromObject(root);root.position.y-=box.min.y;let tint=new THREE.Color(ELEMENTS[template.element]?.color||0xffffff);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material=o.material.clone();o.material.color.lerp(tint,.08+(instance?.evolution||0)*.06)}}});let ring=new THREE.Mesh(new THREE.TorusGeometry(.68,.035,8,40),new THREE.MeshBasicMaterial({color:tint,transparent:true,opacity:.72}));ring.rotation.x=Math.PI/2;ring.position.y=.04;root.add(ring);let mixer=new THREE.AnimationMixer(root),entity={root,mixer,clips:gltf.animations,action:null,home:pos.clone?pos.clone():new THREE.Vector3(pos.x,0,pos.z),side,template,alive:true,materials:[]};root.traverse(o=>{if(o.isMesh)entity.materials.push(o.material)});this.mixers.push(mixer);this.scene.add(root);this.play(entity,'idle');return entity}
 findClip(entity,state){let names=ANIMS[state]||[state];return entity.clips.find(c=>names.some(n=>c.name.toLowerCase().includes(n.toLowerCase())))||entity.clips[0]}
 play(entity,state,once=false){if(!entity?.alive&&state!=='death')return;let clip=this.findClip(entity,state);if(!clip)return;let next=entity.mixer.clipAction(clip);next.reset().setEffectiveTimeScale(1).setEffectiveWeight(1);next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;if(entity.action&&entity.action!==next)entity.action.fadeOut(.12);next.fadeIn(.12).play();entity.action=next}
 async addPet(template,instance,pos={x:0,y:0,z:0},side='ally'){try{return this.makeEntity(await this.load(template),template,instance,new THREE.Vector3(pos.x,pos.y||0,pos.z),side)}catch(e){console.warn('3D model fallback',template.id,e);return this.fallback(template,pos,side)}}
 fallback(template,pos,side){let color=ELEMENTS[template.element]?.color||0xffffff,root=new THREE.Group(),body=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,2),new THREE.MeshStandardMaterial({color}));body.position.y=.72;root.add(body);root.position.set(pos.x,0,pos.z);this.scene.add(root);return {root,mixer:null,clips:[],home:new THREE.Vector3(pos.x,0,pos.z),side,template,alive:true,materials:[body.material]}}
 async setShowcase(t,i){if(this.pet)this.scene.remove(this.pet.root);this.pet=await this.addPet(t,i,{x:0,y:0,z:0});this.pet.root.rotation.y=0;this.play(this.pet,'idle')}
 async setBattle(team,enemies){let allyPos=[new THREE.Vector3(-3.4,0,-.55),new THREE.Vector3(-2.2,0,.45),new THREE.Vector3(-1,0,-.45)],enemyPos=enemies.length===1?[new THREE.Vector3(2.5,0,0)]:[new THREE.Vector3(1.2,0,-.5),new THREE.Vector3(2.4,0,.45),new THREE.Vector3(3.6,0,-.45)];let jobs=[];team.forEach((x,i)=>jobs.push(this.addPet(x.template,x.instance,allyPos[i],'ally').then(e=>this.entities.ally[i]=e)));enemies.forEach((x,i)=>jobs.push(this.addPet(x.template,null,enemyPos[i],'enemy').then(e=>this.entities.enemy[i]=e)));await Promise.all(jobs)}
 tween(entity,to,duration=380,lift=0){let from=entity.root.position.clone(),start=performance.now();return new Promise(resolve=>{let step=now=>{if(this.dead)return resolve();let t=Math.min(1,(now-start)/duration),k=ease(t);entity.root.position.lerpVectors(from,to,k);entity.root.position.y+=Math.sin(Math.PI*t)*lift;if(t<1)requestAnimationFrame(step);else{entity.root.position.copy(to);resolve()}};requestAnimationFrame(step)})}
 async attack(side,index,targetSide,targetIndex,{skill=false,element='fire',heal=false}={}){let actor=this.entities[side]?.[index],target=this.entities[targetSide]?.[targetIndex];if(!actor||!actor.alive)return;if(heal){this.play(actor,'attack',true);this.burst(actor.root.position,element,'heal');await this.delay(650);this.play(actor,'idle');return}if(!target)return;let dir=side==='ally'?1:-1,near=target.root.position.clone();near.x-=dir*1.05;this.play(actor,'move');await this.tween(actor,near,skill?330:420,.22);this.play(actor,'attack',true);await this.delay(180);this.burst(target.root.position,element,skill?'skill':'hit');this.shake(skill?9:5);await this.hit(targetSide,targetIndex);await this.delay(skill?430:260);this.play(actor,'move');await this.tween(actor,actor.home,360,.12);this.play(actor,'idle')}
 async hit(side,index){let e=this.entities[side]?.[index];if(!e||!e.alive)return;this.play(e,'hit',true);let home=e.root.position.clone(),dir=side==='ally'?-1:1;e.materials.forEach(m=>{if(m?.emissive){m.userData.old=m.emissive.getHex();m.emissive.setHex(0xffffff)}});await this.tween(e,new THREE.Vector3(home.x+dir*.25,home.y,home.z),100);await this.tween(e,home,130);e.materials.forEach(m=>{if(m?.emissive)m.emissive.setHex(m.userData.old||0)});this.play(e,'idle')}
 async death(side,index){let e=this.entities[side]?.[index];if(!e||!e.alive)return;e.alive=false;this.play(e,'death',true);await this.delay(650);let start=performance.now();return new Promise(resolve=>{let fade=now=>{let t=Math.min(1,(now-start)/500);e.materials.forEach(m=>{m.transparent=true;m.opacity=1-t});if(t<1)requestAnimationFrame(fade);else resolve()};requestAnimationFrame(fade)})}
 victory(){this.entities.ally.filter(e=>e?.alive).forEach(e=>this.play(e,'victory'))}
 burst(position,element,type){let color=new THREE.Color(ELEMENTS[element]?.color||0xffffff),count=type==='skill'?34:type==='heal'?24:16;for(let i=0;i<count;i++){let mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(type==='skill'?.07:.045),new THREE.MeshBasicMaterial({color:type==='heal'?0x7dffb2:color,transparent:true}));mesh.position.copy(position).add(new THREE.Vector3(0,1,0));this.scene.add(mesh);let velocity=new THREE.Vector3((Math.random()-.5)*3,Math.random()*2.8+.5,(Math.random()-.5)*2),start=performance.now();let fly=now=>{let t=(now-start)/700;if(t>=1){this.scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();return}mesh.position.addScaledVector(velocity,.016);velocity.y-=.055;mesh.material.opacity=1-t;mesh.scale.setScalar(1+(type==='skill'?t*2:0));requestAnimationFrame(fly)};requestAnimationFrame(fly)}if(type==='skill'){let wave=new THREE.Mesh(new THREE.RingGeometry(.2,.32,32),new THREE.MeshBasicMaterial({color,transparent:true,side:THREE.DoubleSide}));wave.rotation.x=-Math.PI/2;wave.position.copy(position).add(new THREE.Vector3(0,.08,0));this.scene.add(wave);let start=performance.now(),grow=now=>{let t=Math.min(1,(now-start)/550);wave.scale.setScalar(1+t*10);wave.material.opacity=1-t;if(t<1)requestAnimationFrame(grow);else this.scene.remove(wave)};requestAnimationFrame(grow)}}
 shake(amount=6){this.renderer.domElement.animate([{transform:'translate(0)'},{transform:`translate(${amount}px,${-amount/2}px)`},{transform:`translate(${-amount}px,${amount/3}px)`},{transform:'translate(0)'}],{duration:260})}
 flash(color=0xffffff){this.renderer.domElement.animate([{filter:'brightness(1)'},{filter:`brightness(1.8) drop-shadow(0 0 20px #${color.toString(16).padStart(6,'0')})`},{filter:'brightness(1)'}],{duration:360})}
 delay(ms){return new Promise(r=>setTimeout(r,ms))}
 resize(){let w=this.host.clientWidth||400,h=this.host.clientHeight||300;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 loop(){if(this.dead)return;requestAnimationFrame(()=>this.loop());let dt=this.clock.getDelta(),t=performance.now()/1000;this.mixers.forEach(m=>m?.update(dt));this.scene.children.forEach(o=>{if(o.userData.float!==undefined)o.position.y+=Math.sin(t+o.userData.float)*.0008});if(this.pet)this.pet.root.rotation.y+=.002;this.renderer.render(this.scene,this.camera)}
 destroy(){this.dead=true;this.observer?.disconnect();this.mixers.forEach(m=>m.stopAllAction());this.renderer.dispose();this.host.innerHTML=''}
}
