import * as THREE from '../vendor/three.module.js';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {ELEMENTS} from './game-data.js';
const cache=new Map();
export class PetRenderer{
 constructor(host,{battle=false,quality='high'}={}){this.host=host;this.battle=battle;this.mixers=[];this.clock=new THREE.Clock();this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(35,1,.1,100);this.camera.position.set(0,battle?5:2.2,battle?11:6);this.camera.lookAt(0,battle?1:1,0);this.renderer=new THREE.WebGLRenderer({antialias:quality==='high',alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.7:1));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.shadowMap.enabled=quality==='high';host.appendChild(this.renderer.domElement);this.loader=new GLTFLoader();this.buildScene();this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.loop()}
 buildScene(){this.scene.add(new THREE.HemisphereLight(0xbfdcff,0x17202e,2.2));let key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,8,5);key.castShadow=true;this.scene.add(key);let rim=new THREE.PointLight(0x8d72ff,15,16);rim.position.set(-5,4,-2);this.scene.add(rim);let floor=new THREE.Mesh(new THREE.CircleGeometry(this.battle?8:3,48),new THREE.MeshStandardMaterial({color:0x172546,roughness:.72,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor);for(let i=0;i<(this.battle?35:18);i++){let g=new THREE.Mesh(new THREE.IcosahedronGeometry(.025+Math.random()*.04),new THREE.MeshBasicMaterial({color:i%2?0x67e7ff:0xb08cff}));g.position.set((Math.random()-.5)*(this.battle?13:6),.2+Math.random()*4,(Math.random()-.5)*5);g.userData.float=Math.random()*6;this.scene.add(g)}}
 async asset(model){let gltf=await new Promise((resolve,reject)=>this.loader.load(`assets/models/${model}.glb`,resolve,undefined,reject));return gltf.scene}
 async addPet(template,instance,pos={x:0,y:0,z:0},enemy=false){try{let root=await this.asset(template.model);root.position.set(pos.x,pos.y,pos.z);root.rotation.y=enemy?-Math.PI/2:Math.PI/2;let box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),scale=(this.battle?1.45:2.2)/Math.max(size.y,.1);root.scale.setScalar(scale);box.setFromObject(root);root.position.y-=box.min.y;root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material=o.material.clone();let c=new THREE.Color(ELEMENTS[template.element]?.color||0xffffff);o.material.color.lerp(c,.2+(instance?.evolution||0)*.08)}}});let ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.035,8,40),new THREE.MeshBasicMaterial({color:ELEMENTS[template.element]?.color||0xffffff,transparent:true,opacity:.65}));ring.rotation.x=Math.PI/2;ring.position.y=.06;root.add(ring);this.scene.add(root);return root}catch(e){let fallback=new THREE.Mesh(new THREE.SphereGeometry(.7,16,12),new THREE.MeshStandardMaterial({color:ELEMENTS[template.element]?.color||0xffffff}));fallback.position.set(pos.x,.7,pos.z);this.scene.add(fallback);return fallback}}
 async setShowcase(t,i){if(this.pet)this.scene.remove(this.pet);this.pet=await this.addPet(t,i);this.pet.rotation.y=0}
 addBattleAvatar(template,instance,pos,enemy=false){let group=new THREE.Group(),base=new THREE.Color(ELEMENTS[template.element]?.color||0xffffff),dark=base.clone().multiplyScalar(.52),mat=new THREE.MeshStandardMaterial({color:base,roughness:.62,metalness:.08}),accent=new THREE.MeshStandardMaterial({color:dark,roughness:.7});let body=new THREE.Mesh(new THREE.IcosahedronGeometry(.58,2),mat),head=new THREE.Mesh(new THREE.IcosahedronGeometry(.46,2),mat);body.scale.set(1,.95,.85);body.position.y=.72;head.position.set(enemy?-.28:.28,1.35,0);group.add(body,head);for(let s of [-1,1]){let leg=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.34,4,8),accent);leg.position.set(-.18,.25,s*.25);group.add(leg);let ear=new THREE.Mesh(new THREE.ConeGeometry(.14,.42,6),mat);ear.position.set(enemy?-.3:.3,1.82,s*.22);ear.rotation.z=enemy?-.25:.25;group.add(ear);let eye=new THREE.Mesh(new THREE.SphereGeometry(.055,8,6),new THREE.MeshBasicMaterial({color:0xffffff}));eye.position.set(enemy?-.69:.69,1.43,s*.17);group.add(eye)}let ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.035,8,36),new THREE.MeshBasicMaterial({color:base,transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2;ring.position.y=.05;group.add(ring);group.position.set(pos.x,0,pos.z);group.userData.bob=Math.random()*6;group.traverse(o=>{if(o.isMesh)o.castShadow=true});this.scene.add(group);return group}
 async setBattle(team,enemies){let xs=[-3.2,-2,-.8];for(let i=0;i<team.length;i++)this.addBattleAvatar(team[i].template,team[i].instance,{x:xs[i],z:i%2?.4:-.4});for(let i=0;i<enemies.length;i++)this.addBattleAvatar(enemies[i].template,null,{x:1.6+i*1.5,z:i%2?.4:-.4},true)}
 resize(){let w=this.host.clientWidth||400,h=this.host.clientHeight||300;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 loop(){if(this.dead)return;requestAnimationFrame(()=>this.loop());let dt=this.clock.getDelta(),t=performance.now()/1000;this.mixers.forEach(m=>m.update(dt));this.scene.children.forEach(o=>{if(o.userData.float!==undefined)o.position.y+=Math.sin(t+o.userData.float)*.0008});if(this.pet)this.pet.rotation.y+=.003;this.renderer.render(this.scene,this.camera)}
 flash(color=0xffffff){this.renderer.domElement.animate([{filter:'brightness(1)'},{filter:`brightness(2) drop-shadow(0 0 20px #${color.toString(16)})`},{filter:'brightness(1)'}],{duration:350})}
 destroy(){this.dead=true;this.observer?.disconnect();this.renderer.dispose();this.host.innerHTML=''}
}
