const KEY='jose_expedition_v2';
const GEAR_BLUEPRINTS=[
 {itemId:'ember_blade',slot:'weapon',name:'餘燼之刃',icon:'🗡️',rarity:'稀有',stat:'攻擊',value:120},
 {itemId:'tide_staff',slot:'weapon',name:'潮汐法杖',icon:'🪄',rarity:'史詩',stat:'魔力',value:145},
 {itemId:'bark_armor',slot:'armor',name:'古樹護甲',icon:'🛡️',rarity:'稀有',stat:'生命',value:520},
 {itemId:'star_cloak',slot:'armor',name:'星痕斗篷',icon:'🥋',rarity:'史詩',stat:'防禦',value:170},
 {itemId:'swift_rune',slot:'rune',name:'疾步符文',icon:'💠',rarity:'精良',stat:'速度',value:38},
 {itemId:'fury_rune',slot:'rune',name:'裂傷符文',icon:'🔶',rarity:'稀有',stat:'暴擊',value:45}
];
function uuid(prefix='p'){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function today(){return new Date().toISOString().slice(0,10)}
function newGear(index=0){let b=GEAR_BLUEPRINTS[index%GEAR_BLUEPRINTS.length];return {...b,uid:uuid('g'),level:1}}
function fresh(pets){
 let starters=pets.filter((_,i)=>[0,1,10,11,20,21].includes(i)).map((p,i)=>({uuid:uuid(),petId:p.id,level:8+i,exp:0,stars:1,shards:20,affinity:0,skillLevel:1,evolution:0,branch:null}));
 return {version:3,createdAt:Date.now(),gold:5000,gems:600,energy:90,maxEnergy:90,energyUpdatedAt:Date.now(),playerLevel:1,playerExp:0,highestStage:1,stageStars:{},inventory:starters,team:starters.slice(0,3).map(p=>p.uuid),materials:{fire:8,forest:8,ocean:8,light:0,dark:0},tickets:10,towerFloor:1,daily:{date:today(),claimed:[]},settings:{quality:'high',sound:true},base:{training:1,lab:1,hatchery:1},items:{exp_small:8,exp_medium:2,revival_potion:3,forge_core:12,rune_dust:6},gearBag:[newGear(0),newGear(2),newGear(4)],equipment:{},lastOfflineClaim:Date.now(),stats:{battles:0,enhancements:0,offlineClaims:0}};
}
export class Store{
 constructor(pets){this.pets=Array.isArray(pets)?pets:[];try{this.state=JSON.parse(localStorage.getItem(KEY))||fresh(this.pets)}catch(_){this.state=fresh(this.pets)}this.migrate();this.save()}
 migrate(){
  let s=this.state;if(!s||typeof s!=='object')s=this.state=fresh(this.pets);s.version=3;s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.stageStars=s.stageStars||{};s.highestStage=Math.min(60,Math.max(1,Number(s.highestStage)||1));s.materials=s.materials||{fire:5,forest:5,ocean:5,light:0,dark:0};s.team=Array.isArray(s.team)?s.team:s.inventory.slice(0,3).map(p=>p.uuid);s.base=s.base||{training:1,lab:1,hatchery:1};s.settings=s.settings||{quality:'high',sound:true};s.items={exp_small:0,exp_medium:0,revival_potion:0,forge_core:0,rune_dust:0,...s.items};s.gearBag=Array.isArray(s.gearBag)?s.gearBag:[];s.equipment=s.equipment||{};s.lastOfflineClaim=Number(s.lastOfflineClaim)||Date.now();s.stats={battles:0,enhancements:0,offlineClaims:0,...s.stats};s.daily=s.daily||{date:today(),claimed:[]};if(s.daily.date!==today())s.daily={date:today(),claimed:[]};let now=Date.now(),last=Number(s.energyUpdatedAt)||now,gained=Math.floor((now-last)/300000);if(gained>0){s.energy=Math.min(s.maxEnergy,s.energy+gained);s.energyUpdatedAt=last+gained*300000}else s.energyUpdatedAt=last;
  s.inventory.forEach(p=>{p.shards??=0;p.affinity??=0;p.skillLevel??=1;p.evolution??=0;p.branch??=null;p.exp??=0});
 }
 save(){localStorage.setItem(KEY,JSON.stringify(this.state));window.dispatchEvent(new CustomEvent('statechange'))}
 pet(id){return this.state.inventory.find(p=>p.uuid===id)}
 template(id){return this.pets.find(p=>p.id===id)}
 addPet(id){let owned=this.state.inventory.find(p=>p.petId===id);if(owned){owned.shards+=20;return {duplicate:true,pet:owned}}let p={uuid:uuid(),petId:id,level:1,exp:0,stars:1,shards:0,affinity:0,skillLevel:1,evolution:0,branch:null};this.state.inventory.push(p);return {duplicate:false,pet:p}}
 summon(count){if(count!==1&&count!==10||!this.pets.length)return null;let cost=count===10?9:1;if(this.state.tickets<cost&&this.state.gems<cost*100)return null;if(this.state.tickets>=cost)this.state.tickets-=cost;else this.state.gems-=cost*100;let results=[];for(let i=0;i<count;i++){let roll=Math.random(),pool=this.pets.filter(p=>roll<.03?p.quality==='legendary':roll<.15?['epic','elite'].includes(p.quality):['normal','rare','elite'].includes(p.quality));if(!pool.length)pool=this.pets;results.push(this.addPet(pool[Math.floor(Math.random()*pool.length)].id))}this.save();return results}
 levelPet(id){let p=this.pet(id);if(!p||p.level>=100)return false;let cost=p.level*90;if(this.state.gold<cost)return false;this.state.gold-=cost;p.level++;p.affinity=Math.min(100,p.affinity+1);this.state.stats.enhancements++;this.save();return true}
 upgradeSkill(id){let p=this.pet(id);if(!p||p.skillLevel>=10)return false;let cost=p.skillLevel*600;if(this.state.gold<cost)return false;this.state.gold-=cost;p.skillLevel++;this.state.stats.enhancements++;this.save();return true}
 useExpItem(id,itemId){let p=this.pet(id),values={exp_small:120,exp_medium:800};if(!p||!values[itemId]||(this.state.items[itemId]||0)<1||p.level>=100)return false;this.state.items[itemId]--;p.exp+=values[itemId];while(p.level<100&&p.exp>=p.level*80){p.exp-=p.level*80;p.level++}this.state.stats.enhancements++;this.save();return true}
 starPet(id){let p=this.pet(id);if(!p||p.stars>=5)return false;let need=p.stars*20;if(p.shards<need)return false;p.shards-=need;p.stars++;this.state.stats.enhancements++;this.save();return true}
 evolve(id,branch){let p=this.pet(id);if(!p)return false;let t=this.template(p.petId);if(!t)return false;let need=p.evolution?50:20;if(p.level<(p.evolution?50:20)||(this.state.materials[t.element]||0)<need)return false;this.state.materials[t.element]-=need;p.evolution++;if(p.evolution===2)p.branch=branch;this.state.stats.enhancements++;this.save();return true}
 setTeam(id){let a=this.state.team,i=a.indexOf(id);if(i>=0)a.splice(i,1);else{if(a.length>=3)a.shift();a.push(id)}this.save()}
 forgeGear(){if(this.state.gold<1200||(this.state.items.forge_core||0)<3)return null;this.state.gold-=1200;this.state.items.forge_core-=3;let gear=newGear(Math.floor(Math.random()*GEAR_BLUEPRINTS.length));this.state.gearBag.push(gear);this.save();return gear}
 upgradeGear(uid){let gear=this.state.gearBag.find(g=>g.uid===uid);if(!gear||gear.level>=10)return false;let cost=gear.level*700;if(this.state.gold<cost||(this.state.items.rune_dust||0)<1)return false;this.state.gold-=cost;this.state.items.rune_dust--;gear.level++;this.state.stats.enhancements++;this.save();return true}
 equipGear(petId,uid){let pet=this.pet(petId),gear=this.state.gearBag.find(g=>g.uid===uid);if(!pet||!gear)return false;Object.values(this.state.equipment).forEach(slots=>{if(slots)Object.keys(slots).forEach(k=>{if(slots[k]===uid)slots[k]=null})});let slots=this.state.equipment[petId]||(this.state.equipment[petId]={weapon:null,armor:null,rune:null});slots[gear.slot]=uid;this.save();return true}
 gearForPet(id){let slots=this.state.equipment[id]||{};return Object.values(slots).map(uid=>this.state.gearBag.find(g=>g.uid===uid)).filter(Boolean)}
 claimOffline(){let now=Date.now(),hours=Math.min(8,Math.max(0,(now-this.state.lastOfflineClaim)/3600000));if(hours<.02)return null;let gold=Math.floor(hours*this.state.base.training*420),potions=Math.max(1,Math.floor(hours/2));this.state.gold+=gold;this.state.items.exp_small+=potions;this.state.lastOfflineClaim=now;this.state.stats.offlineClaims++;this.save();return {hours,gold,potions}}
 claimMission(id){if(this.state.daily.date!==today())this.state.daily={date:today(),claimed:[]};if(this.state.daily.claimed.includes(id))return null;let goals={battle:this.state.stats.battles>=1,enhance:this.state.stats.enhancements>=2,offline:this.state.stats.offlineClaims>=1};if(!goals[id])return null;let reward=id==='battle'?{gold:800}:{gems:60};this.state.gold+=reward.gold||0;this.state.gems+=reward.gems||0;this.state.daily.claimed.push(id);this.save();return reward}
 completeStage(info,stars){let key=info.id;this.state.stageStars[key]=Math.max(this.state.stageStars[key]||0,stars);this.state.highestStage=Math.min(60,Math.max(this.state.highestStage,info.regionIndex*12+info.stage+1));this.state.gold+=info.level*65*(info.boss?4:1);this.state.materials[info.element]=(this.state.materials[info.element]||0)+(info.boss?8:2);this.state.items.forge_core+=(info.elite||info.boss)?2:1;if(info.boss)this.state.items.rune_dust+=2;this.state.stats.battles++;this.state.playerExp+=info.level*20;while(this.state.playerExp>=this.state.playerLevel*150){this.state.playerExp-=this.state.playerLevel*150;this.state.playerLevel++;this.state.maxEnergy++}this.save()}
 reset(){this.state=fresh(this.pets);this.save()}
}
